-- Run this in your Supabase SQL Editor

-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  stock int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create customers table
create table public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  address text,
  previous_due numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create bills table
create table public.bills (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers not null,
  total_amount numeric not null,
  discount numeric default 0,
  paid_amount numeric default 0,
  due_amount numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create bill_items table
create table public.bill_items (
  id bigint generated by default as identity primary key,
  bill_id bigint references public.bills not null,
  product_id bigint references public.products not null,
  quantity int not null,
  price_at_time numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
